/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.enums;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ContributionState implements EnumType {

    complete("complete"),

    incomplete("incomplete"),

    deleted("deleted");

    private final String literal;

    private ContributionState(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public String getName() {
        return "contribution_state";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
