/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.enums;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EntryType implements EnumType {

    section("section"),

    care_entry("care_entry"),

    admin("admin"),

    proxy("proxy");

    private final String literal;

    private EntryType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public String getName() {
        return "entry_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
