/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.tables.Access;
import org.ehrbase.jooq.pg.tables.Attestation;
import org.ehrbase.jooq.pg.tables.AttestationRef;
import org.ehrbase.jooq.pg.tables.AttestedView;
import org.ehrbase.jooq.pg.tables.AuditDetails;
import org.ehrbase.jooq.pg.tables.CompoXref;
import org.ehrbase.jooq.pg.tables.Composition;
import org.ehrbase.jooq.pg.tables.CompositionHistory;
import org.ehrbase.jooq.pg.tables.Concept;
import org.ehrbase.jooq.pg.tables.Contribution;
import org.ehrbase.jooq.pg.tables.Ehr;
import org.ehrbase.jooq.pg.tables.Entry;
import org.ehrbase.jooq.pg.tables.EntryHistory;
import org.ehrbase.jooq.pg.tables.EventContext;
import org.ehrbase.jooq.pg.tables.EventContextHistory;
import org.ehrbase.jooq.pg.tables.FlywaySchemaHistory;
import org.ehrbase.jooq.pg.tables.Folder;
import org.ehrbase.jooq.pg.tables.FolderHierarchy;
import org.ehrbase.jooq.pg.tables.FolderHierarchyHistory;
import org.ehrbase.jooq.pg.tables.FolderHistory;
import org.ehrbase.jooq.pg.tables.FolderItems;
import org.ehrbase.jooq.pg.tables.FolderItemsHistory;
import org.ehrbase.jooq.pg.tables.Heading;
import org.ehrbase.jooq.pg.tables.Language;
import org.ehrbase.jooq.pg.tables.ObjectRef;
import org.ehrbase.jooq.pg.tables.ObjectRefHistory;
import org.ehrbase.jooq.pg.tables.Participation;
import org.ehrbase.jooq.pg.tables.ParticipationHistory;
import org.ehrbase.jooq.pg.tables.PartyIdentified;
import org.ehrbase.jooq.pg.tables.SessionLog;
import org.ehrbase.jooq.pg.tables.Status;
import org.ehrbase.jooq.pg.tables.StatusHistory;
import org.ehrbase.jooq.pg.tables.StoredQuery;
import org.ehrbase.jooq.pg.tables.System;
import org.ehrbase.jooq.pg.tables.TemplateStore;
import org.ehrbase.jooq.pg.tables.TerminologyProvider;
import org.ehrbase.jooq.pg.tables.Territory;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>ehr</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCESS_PKEY = Indexes0.ACCESS_PKEY;
    public static final Index ATTESTATION_PKEY = Indexes0.ATTESTATION_PKEY;
    public static final Index ATTESTATION_REFERENCE_IDX = Indexes0.ATTESTATION_REFERENCE_IDX;
    public static final Index ATTESTATION_REF_PKEY = Indexes0.ATTESTATION_REF_PKEY;
    public static final Index ATTESTED_VIEW_ATTESTATION_IDX = Indexes0.ATTESTED_VIEW_ATTESTATION_IDX;
    public static final Index ATTESTED_VIEW_PKEY = Indexes0.ATTESTED_VIEW_PKEY;
    public static final Index AUDIT_DETAILS_PKEY = Indexes0.AUDIT_DETAILS_PKEY;
    public static final Index COMPO_XREF_CHILD_IDX = Indexes0.COMPO_XREF_CHILD_IDX;
    public static final Index EHR_COMPO_XREF = Indexes0.EHR_COMPO_XREF;
    public static final Index COMPOSITION_COMPOSER_IDX = Indexes0.COMPOSITION_COMPOSER_IDX;
    public static final Index COMPOSITION_EHR_IDX = Indexes0.COMPOSITION_EHR_IDX;
    public static final Index COMPOSITION_PKEY = Indexes0.COMPOSITION_PKEY;
    public static final Index COMPOSITION_HISTORY_EHR_IDX = Indexes0.COMPOSITION_HISTORY_EHR_IDX;
    public static final Index EHR_COMPOSITION_HISTORY = Indexes0.EHR_COMPOSITION_HISTORY;
    public static final Index CONCEPT_PKEY = Indexes0.CONCEPT_PKEY;
    public static final Index CONTRIBUTION_EHR_IDX = Indexes0.CONTRIBUTION_EHR_IDX;
    public static final Index CONTRIBUTION_PKEY = Indexes0.CONTRIBUTION_PKEY;
    public static final Index EHR_FOLDER_IDX = Indexes0.EHR_FOLDER_IDX;
    public static final Index EHR_PKEY = Indexes0.EHR_PKEY;
    public static final Index ENTRY_COMPOSITION_ID_IDX = Indexes0.ENTRY_COMPOSITION_ID_IDX;
    public static final Index ENTRY_PKEY = Indexes0.ENTRY_PKEY;
    public static final Index GIN_ENTRY_PATH_IDX = Indexes0.GIN_ENTRY_PATH_IDX;
    public static final Index TEMPLATE_ENTRY_IDX = Indexes0.TEMPLATE_ENTRY_IDX;
    public static final Index EHR_ENTRY_HISTORY = Indexes0.EHR_ENTRY_HISTORY;
    public static final Index ENTRY_HISTORY_COMPOSITION_IDX = Indexes0.ENTRY_HISTORY_COMPOSITION_IDX;
    public static final Index CONTEXT_COMPOSITION_ID_IDX = Indexes0.CONTEXT_COMPOSITION_ID_IDX;
    public static final Index CONTEXT_FACILITY_IDX = Indexes0.CONTEXT_FACILITY_IDX;
    public static final Index CONTEXT_SETTING_IDX = Indexes0.CONTEXT_SETTING_IDX;
    public static final Index EVENT_CONTEXT_PKEY = Indexes0.EVENT_CONTEXT_PKEY;
    public static final Index EHR_EVENT_CONTEXT_HISTORY = Indexes0.EHR_EVENT_CONTEXT_HISTORY;
    public static final Index EVENT_CONTEXT_HISTORY_COMPOSITION_IDX = Indexes0.EVENT_CONTEXT_HISTORY_COMPOSITION_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index FOLDER_IN_CONTRIBUTION_IDX = Indexes0.FOLDER_IN_CONTRIBUTION_IDX;
    public static final Index FOLDER_PK = Indexes0.FOLDER_PK;
    public static final Index FKI_FOLDER_HIERARCHY_PARENT_FK = Indexes0.FKI_FOLDER_HIERARCHY_PARENT_FK;
    public static final Index FOLDER_HIERARCHY_IN_CONTRIBUTION_IDX = Indexes0.FOLDER_HIERARCHY_IN_CONTRIBUTION_IDX;
    public static final Index FOLDER_HIERARCHY_PKEY = Indexes0.FOLDER_HIERARCHY_PKEY;
    public static final Index UQ_FOLDERHIERARCHY_PARENT_CHILD = Indexes0.UQ_FOLDERHIERARCHY_PARENT_CHILD;
    public static final Index FOLDER_HIERARCHY_HISTORY_CONTRIBUTION_IDX = Indexes0.FOLDER_HIERARCHY_HISTORY_CONTRIBUTION_IDX;
    public static final Index FOLDER_HIERARCHY_HISTORY_PKEY = Indexes0.FOLDER_HIERARCHY_HISTORY_PKEY;
    public static final Index FOLDER_HISTORY_CONTRIBUTION_IDX = Indexes0.FOLDER_HISTORY_CONTRIBUTION_IDX;
    public static final Index FOLDER_HISTORY_PKEY = Indexes0.FOLDER_HISTORY_PKEY;
    public static final Index FOLDER_ITEMS_CONTRIBUTION_IDX = Indexes0.FOLDER_ITEMS_CONTRIBUTION_IDX;
    public static final Index FOLDER_ITEMS_PKEY = Indexes0.FOLDER_ITEMS_PKEY;
    public static final Index FOLDER_HIST_IDX = Indexes0.FOLDER_HIST_IDX;
    public static final Index FOLDER_ITEMS_HIST_PKEY = Indexes0.FOLDER_ITEMS_HIST_PKEY;
    public static final Index FOLDER_ITEMS_HISTORY_CONTRIBUTION_IDX = Indexes0.FOLDER_ITEMS_HISTORY_CONTRIBUTION_IDX;
    public static final Index HEADING_PKEY = Indexes0.HEADING_PKEY;
    public static final Index LANGUAGE_PKEY = Indexes0.LANGUAGE_PKEY;
    public static final Index OBJ_REF_IN_CONTRIBUTION_IDX = Indexes0.OBJ_REF_IN_CONTRIBUTION_IDX;
    public static final Index OBJECT_REF_PKEY = Indexes0.OBJECT_REF_PKEY;
    public static final Index OBJECT_REF_HIST_PKEY = Indexes0.OBJECT_REF_HIST_PKEY;
    public static final Index OBJECT_REF_HISTORY_CONTRIBUTION_IDX = Indexes0.OBJECT_REF_HISTORY_CONTRIBUTION_IDX;
    public static final Index CONTEXT_PARTICIPATION_INDEX = Indexes0.CONTEXT_PARTICIPATION_INDEX;
    public static final Index PARTICIPATION_PKEY = Indexes0.PARTICIPATION_PKEY;
    public static final Index EHR_PARTICIPATION_HISTORY = Indexes0.EHR_PARTICIPATION_HISTORY;
    public static final Index PARTICIPATION_HISTORY_EVENT_CONTEXT_IDX = Indexes0.PARTICIPATION_HISTORY_EVENT_CONTEXT_IDX;
    public static final Index PARTY_IDENTIFIED_PARTY_REF_IDX = Indexes0.PARTY_IDENTIFIED_PARTY_REF_IDX;
    public static final Index PARTY_IDENTIFIED_PARTY_TYPE_IDX = Indexes0.PARTY_IDENTIFIED_PARTY_TYPE_IDX;
    public static final Index PARTY_IDENTIFIED_PKEY = Indexes0.PARTY_IDENTIFIED_PKEY;
    public static final Index SESSION_LOG_PKEY = Indexes0.SESSION_LOG_PKEY;
    public static final Index STATUS_EHR_IDX = Indexes0.STATUS_EHR_IDX;
    public static final Index STATUS_PARTY_IDX = Indexes0.STATUS_PARTY_IDX;
    public static final Index STATUS_PKEY = Indexes0.STATUS_PKEY;
    public static final Index EHR_STATUS_HISTORY = Indexes0.EHR_STATUS_HISTORY;
    public static final Index STATUS_HISTORY_EHR_IDX = Indexes0.STATUS_HISTORY_EHR_IDX;
    public static final Index PK_QUALIFIED_NAME = Indexes0.PK_QUALIFIED_NAME;
    public static final Index SYSTEM_PKEY = Indexes0.SYSTEM_PKEY;
    public static final Index TEMPLATE_STORE_PKEY = Indexes0.TEMPLATE_STORE_PKEY;
    public static final Index TERMINOLOGY_PROVIDER_PKEY = Indexes0.TERMINOLOGY_PROVIDER_PKEY;
    public static final Index TERRITORY_CODE_INDEX = Indexes0.TERRITORY_CODE_INDEX;
    public static final Index TERRITORY_PKEY = Indexes0.TERRITORY_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCESS_PKEY = Internal.createIndex("access_pkey", Access.ACCESS, new OrderField[] { Access.ACCESS.ID }, true);
        public static Index ATTESTATION_PKEY = Internal.createIndex("attestation_pkey", Attestation.ATTESTATION, new OrderField[] { Attestation.ATTESTATION.ID }, true);
        public static Index ATTESTATION_REFERENCE_IDX = Internal.createIndex("attestation_reference_idx", Attestation.ATTESTATION, new OrderField[] { Attestation.ATTESTATION.REFERENCE }, false);
        public static Index ATTESTATION_REF_PKEY = Internal.createIndex("attestation_ref_pkey", AttestationRef.ATTESTATION_REF, new OrderField[] { AttestationRef.ATTESTATION_REF.REF }, true);
        public static Index ATTESTED_VIEW_ATTESTATION_IDX = Internal.createIndex("attested_view_attestation_idx", AttestedView.ATTESTED_VIEW, new OrderField[] { AttestedView.ATTESTED_VIEW.ATTESTATION_ID }, false);
        public static Index ATTESTED_VIEW_PKEY = Internal.createIndex("attested_view_pkey", AttestedView.ATTESTED_VIEW, new OrderField[] { AttestedView.ATTESTED_VIEW.ID }, true);
        public static Index AUDIT_DETAILS_PKEY = Internal.createIndex("audit_details_pkey", AuditDetails.AUDIT_DETAILS, new OrderField[] { AuditDetails.AUDIT_DETAILS.ID }, true);
        public static Index COMPO_XREF_CHILD_IDX = Internal.createIndex("compo_xref_child_idx", CompoXref.COMPO_XREF, new OrderField[] { CompoXref.COMPO_XREF.CHILD_UUID }, false);
        public static Index EHR_COMPO_XREF = Internal.createIndex("ehr_compo_xref", CompoXref.COMPO_XREF, new OrderField[] { CompoXref.COMPO_XREF.MASTER_UUID }, false);
        public static Index COMPOSITION_COMPOSER_IDX = Internal.createIndex("composition_composer_idx", Composition.COMPOSITION, new OrderField[] { Composition.COMPOSITION.COMPOSER }, false);
        public static Index COMPOSITION_EHR_IDX = Internal.createIndex("composition_ehr_idx", Composition.COMPOSITION, new OrderField[] { Composition.COMPOSITION.ID, Composition.COMPOSITION.EHR_ID }, false);
        public static Index COMPOSITION_PKEY = Internal.createIndex("composition_pkey", Composition.COMPOSITION, new OrderField[] { Composition.COMPOSITION.ID, Composition.COMPOSITION.EHR_ID }, true);
        public static Index COMPOSITION_HISTORY_EHR_IDX = Internal.createIndex("composition_history_ehr_idx", CompositionHistory.COMPOSITION_HISTORY, new OrderField[] { CompositionHistory.COMPOSITION_HISTORY.EHR_ID }, false);
        public static Index EHR_COMPOSITION_HISTORY = Internal.createIndex("ehr_composition_history", CompositionHistory.COMPOSITION_HISTORY, new OrderField[] { CompositionHistory.COMPOSITION_HISTORY.ID }, false);
        public static Index CONCEPT_PKEY = Internal.createIndex("concept_pkey", Concept.CONCEPT, new OrderField[] { Concept.CONCEPT.ID }, true);
        public static Index CONTRIBUTION_EHR_IDX = Internal.createIndex("contribution_ehr_idx", Contribution.CONTRIBUTION, new OrderField[] { Contribution.CONTRIBUTION.EHR_ID }, false);
        public static Index CONTRIBUTION_PKEY = Internal.createIndex("contribution_pkey", Contribution.CONTRIBUTION, new OrderField[] { Contribution.CONTRIBUTION.ID }, true);
        public static Index EHR_FOLDER_IDX = Internal.createIndex("ehr_folder_idx", Ehr.EHR_, new OrderField[] { Ehr.EHR_.DIRECTORY }, true);
        public static Index EHR_PKEY = Internal.createIndex("ehr_pkey", Ehr.EHR_, new OrderField[] { Ehr.EHR_.ID }, true);
        public static Index ENTRY_COMPOSITION_ID_IDX = Internal.createIndex("entry_composition_id_idx", Entry.ENTRY, new OrderField[] { Entry.ENTRY.COMPOSITION_ID, Entry.ENTRY.EHR_ID }, false);
        public static Index ENTRY_PKEY = Internal.createIndex("entry_pkey", Entry.ENTRY, new OrderField[] { Entry.ENTRY.ID, Entry.ENTRY.EHR_ID }, true);
        public static Index GIN_ENTRY_PATH_IDX = Internal.createIndex("gin_entry_path_idx", Entry.ENTRY, new OrderField[] { Entry.ENTRY.ENTRY_ }, false);
        public static Index TEMPLATE_ENTRY_IDX = Internal.createIndex("template_entry_idx", Entry.ENTRY, new OrderField[] { Entry.ENTRY.TEMPLATE_ID }, false);
        public static Index EHR_ENTRY_HISTORY = Internal.createIndex("ehr_entry_history", EntryHistory.ENTRY_HISTORY, new OrderField[] { EntryHistory.ENTRY_HISTORY.ID }, false);
        public static Index ENTRY_HISTORY_COMPOSITION_IDX = Internal.createIndex("entry_history_composition_idx", EntryHistory.ENTRY_HISTORY, new OrderField[] { EntryHistory.ENTRY_HISTORY.COMPOSITION_ID }, false);
        public static Index CONTEXT_COMPOSITION_ID_IDX = Internal.createIndex("context_composition_id_idx", EventContext.EVENT_CONTEXT, new OrderField[] { EventContext.EVENT_CONTEXT.COMPOSITION_ID, EventContext.EVENT_CONTEXT.EHR_ID }, false);
        public static Index CONTEXT_FACILITY_IDX = Internal.createIndex("context_facility_idx", EventContext.EVENT_CONTEXT, new OrderField[] { EventContext.EVENT_CONTEXT.FACILITY }, false);
        public static Index CONTEXT_SETTING_IDX = Internal.createIndex("context_setting_idx", EventContext.EVENT_CONTEXT, new OrderField[] { EventContext.EVENT_CONTEXT.SETTING }, false);
        public static Index EVENT_CONTEXT_PKEY = Internal.createIndex("event_context_pkey", EventContext.EVENT_CONTEXT, new OrderField[] { EventContext.EVENT_CONTEXT.ID, EventContext.EVENT_CONTEXT.EHR_ID }, true);
        public static Index EHR_EVENT_CONTEXT_HISTORY = Internal.createIndex("ehr_event_context_history", EventContextHistory.EVENT_CONTEXT_HISTORY, new OrderField[] { EventContextHistory.EVENT_CONTEXT_HISTORY.ID }, false);
        public static Index EVENT_CONTEXT_HISTORY_COMPOSITION_IDX = Internal.createIndex("event_context_history_composition_idx", EventContextHistory.EVENT_CONTEXT_HISTORY, new OrderField[] { EventContextHistory.EVENT_CONTEXT_HISTORY.COMPOSITION_ID }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index FOLDER_IN_CONTRIBUTION_IDX = Internal.createIndex("folder_in_contribution_idx", Folder.FOLDER, new OrderField[] { Folder.FOLDER.IN_CONTRIBUTION }, false);
        public static Index FOLDER_PK = Internal.createIndex("folder_pk", Folder.FOLDER, new OrderField[] { Folder.FOLDER.ID }, true);
        public static Index FKI_FOLDER_HIERARCHY_PARENT_FK = Internal.createIndex("fki_folder_hierarchy_parent_fk", FolderHierarchy.FOLDER_HIERARCHY, new OrderField[] { FolderHierarchy.FOLDER_HIERARCHY.PARENT_FOLDER }, false);
        public static Index FOLDER_HIERARCHY_IN_CONTRIBUTION_IDX = Internal.createIndex("folder_hierarchy_in_contribution_idx", FolderHierarchy.FOLDER_HIERARCHY, new OrderField[] { FolderHierarchy.FOLDER_HIERARCHY.IN_CONTRIBUTION }, false);
        public static Index FOLDER_HIERARCHY_PKEY = Internal.createIndex("folder_hierarchy_pkey", FolderHierarchy.FOLDER_HIERARCHY, new OrderField[] { FolderHierarchy.FOLDER_HIERARCHY.PARENT_FOLDER, FolderHierarchy.FOLDER_HIERARCHY.CHILD_FOLDER }, true);
        public static Index UQ_FOLDERHIERARCHY_PARENT_CHILD = Internal.createIndex("uq_folderhierarchy_parent_child", FolderHierarchy.FOLDER_HIERARCHY, new OrderField[] { FolderHierarchy.FOLDER_HIERARCHY.PARENT_FOLDER, FolderHierarchy.FOLDER_HIERARCHY.CHILD_FOLDER }, true);
        public static Index FOLDER_HIERARCHY_HISTORY_CONTRIBUTION_IDX = Internal.createIndex("folder_hierarchy_history_contribution_idx", FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY, new OrderField[] { FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY.IN_CONTRIBUTION }, false);
        public static Index FOLDER_HIERARCHY_HISTORY_PKEY = Internal.createIndex("folder_hierarchy_history_pkey", FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY, new OrderField[] { FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY.PARENT_FOLDER, FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY.CHILD_FOLDER, FolderHierarchyHistory.FOLDER_HIERARCHY_HISTORY.IN_CONTRIBUTION }, true);
        public static Index FOLDER_HISTORY_CONTRIBUTION_IDX = Internal.createIndex("folder_history_contribution_idx", FolderHistory.FOLDER_HISTORY, new OrderField[] { FolderHistory.FOLDER_HISTORY.IN_CONTRIBUTION }, false);
        public static Index FOLDER_HISTORY_PKEY = Internal.createIndex("folder_history_pkey", FolderHistory.FOLDER_HISTORY, new OrderField[] { FolderHistory.FOLDER_HISTORY.ID, FolderHistory.FOLDER_HISTORY.IN_CONTRIBUTION }, true);
        public static Index FOLDER_ITEMS_CONTRIBUTION_IDX = Internal.createIndex("folder_items_contribution_idx", FolderItems.FOLDER_ITEMS, new OrderField[] { FolderItems.FOLDER_ITEMS.IN_CONTRIBUTION }, false);
        public static Index FOLDER_ITEMS_PKEY = Internal.createIndex("folder_items_pkey", FolderItems.FOLDER_ITEMS, new OrderField[] { FolderItems.FOLDER_ITEMS.FOLDER_ID, FolderItems.FOLDER_ITEMS.OBJECT_REF_ID, FolderItems.FOLDER_ITEMS.IN_CONTRIBUTION }, true);
        public static Index FOLDER_HIST_IDX = Internal.createIndex("folder_hist_idx", FolderItemsHistory.FOLDER_ITEMS_HISTORY, new OrderField[] { FolderItemsHistory.FOLDER_ITEMS_HISTORY.FOLDER_ID, FolderItemsHistory.FOLDER_ITEMS_HISTORY.OBJECT_REF_ID, FolderItemsHistory.FOLDER_ITEMS_HISTORY.IN_CONTRIBUTION }, false);
        public static Index FOLDER_ITEMS_HIST_PKEY = Internal.createIndex("folder_items_hist_pkey", FolderItemsHistory.FOLDER_ITEMS_HISTORY, new OrderField[] { FolderItemsHistory.FOLDER_ITEMS_HISTORY.FOLDER_ID, FolderItemsHistory.FOLDER_ITEMS_HISTORY.OBJECT_REF_ID, FolderItemsHistory.FOLDER_ITEMS_HISTORY.IN_CONTRIBUTION }, true);
        public static Index FOLDER_ITEMS_HISTORY_CONTRIBUTION_IDX = Internal.createIndex("folder_items_history_contribution_idx", FolderItemsHistory.FOLDER_ITEMS_HISTORY, new OrderField[] { FolderItemsHistory.FOLDER_ITEMS_HISTORY.IN_CONTRIBUTION }, false);
        public static Index HEADING_PKEY = Internal.createIndex("heading_pkey", Heading.HEADING, new OrderField[] { Heading.HEADING.CODE }, true);
        public static Index LANGUAGE_PKEY = Internal.createIndex("language_pkey", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.CODE }, true);
        public static Index OBJ_REF_IN_CONTRIBUTION_IDX = Internal.createIndex("obj_ref_in_contribution_idx", ObjectRef.OBJECT_REF, new OrderField[] { ObjectRef.OBJECT_REF.IN_CONTRIBUTION }, false);
        public static Index OBJECT_REF_PKEY = Internal.createIndex("object_ref_pkey", ObjectRef.OBJECT_REF, new OrderField[] { ObjectRef.OBJECT_REF.ID, ObjectRef.OBJECT_REF.IN_CONTRIBUTION }, true);
        public static Index OBJECT_REF_HIST_PKEY = Internal.createIndex("object_ref_hist_pkey", ObjectRefHistory.OBJECT_REF_HISTORY, new OrderField[] { ObjectRefHistory.OBJECT_REF_HISTORY.ID, ObjectRefHistory.OBJECT_REF_HISTORY.IN_CONTRIBUTION }, true);
        public static Index OBJECT_REF_HISTORY_CONTRIBUTION_IDX = Internal.createIndex("object_ref_history_contribution_idx", ObjectRefHistory.OBJECT_REF_HISTORY, new OrderField[] { ObjectRefHistory.OBJECT_REF_HISTORY.IN_CONTRIBUTION }, false);
        public static Index CONTEXT_PARTICIPATION_INDEX = Internal.createIndex("context_participation_index", Participation.PARTICIPATION, new OrderField[] { Participation.PARTICIPATION.EVENT_CONTEXT }, false);
        public static Index PARTICIPATION_PKEY = Internal.createIndex("participation_pkey", Participation.PARTICIPATION, new OrderField[] { Participation.PARTICIPATION.ID }, true);
        public static Index EHR_PARTICIPATION_HISTORY = Internal.createIndex("ehr_participation_history", ParticipationHistory.PARTICIPATION_HISTORY, new OrderField[] { ParticipationHistory.PARTICIPATION_HISTORY.ID }, false);
        public static Index PARTICIPATION_HISTORY_EVENT_CONTEXT_IDX = Internal.createIndex("participation_history_event_context_idx", ParticipationHistory.PARTICIPATION_HISTORY, new OrderField[] { ParticipationHistory.PARTICIPATION_HISTORY.EVENT_CONTEXT }, false);
        public static Index PARTY_IDENTIFIED_PARTY_REF_IDX = Internal.createIndex("party_identified_party_ref_idx", PartyIdentified.PARTY_IDENTIFIED, new OrderField[] { PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_NAMESPACE, PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_SCHEME, PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_VALUE }, false);
        public static Index PARTY_IDENTIFIED_PARTY_TYPE_IDX = Internal.createIndex("party_identified_party_type_idx", PartyIdentified.PARTY_IDENTIFIED, new OrderField[] { PartyIdentified.PARTY_IDENTIFIED.PARTY_TYPE, PartyIdentified.PARTY_IDENTIFIED.NAME }, false);
        public static Index PARTY_IDENTIFIED_PKEY = Internal.createIndex("party_identified_pkey", PartyIdentified.PARTY_IDENTIFIED, new OrderField[] { PartyIdentified.PARTY_IDENTIFIED.ID }, true);
        public static Index SESSION_LOG_PKEY = Internal.createIndex("session_log_pkey", SessionLog.SESSION_LOG, new OrderField[] { SessionLog.SESSION_LOG.ID }, true);
        public static Index STATUS_EHR_IDX = Internal.createIndex("status_ehr_idx", Status.STATUS, new OrderField[] { Status.STATUS.EHR_ID }, false);
        public static Index STATUS_PARTY_IDX = Internal.createIndex("status_party_idx", Status.STATUS, new OrderField[] { Status.STATUS.PARTY }, false);
        public static Index STATUS_PKEY = Internal.createIndex("status_pkey", Status.STATUS, new OrderField[] { Status.STATUS.ID, Status.STATUS.EHR_ID }, true);
        public static Index EHR_STATUS_HISTORY = Internal.createIndex("ehr_status_history", StatusHistory.STATUS_HISTORY, new OrderField[] { StatusHistory.STATUS_HISTORY.ID }, false);
        public static Index STATUS_HISTORY_EHR_IDX = Internal.createIndex("status_history_ehr_idx", StatusHistory.STATUS_HISTORY, new OrderField[] { StatusHistory.STATUS_HISTORY.EHR_ID }, false);
        public static Index PK_QUALIFIED_NAME = Internal.createIndex("pk_qualified_name", StoredQuery.STORED_QUERY, new OrderField[] { StoredQuery.STORED_QUERY.REVERSE_DOMAIN_NAME, StoredQuery.STORED_QUERY.SEMANTIC_ID, StoredQuery.STORED_QUERY.SEMVER }, true);
        public static Index SYSTEM_PKEY = Internal.createIndex("system_pkey", System.SYSTEM, new OrderField[] { System.SYSTEM.ID }, true);
        public static Index TEMPLATE_STORE_PKEY = Internal.createIndex("template_store_pkey", TemplateStore.TEMPLATE_STORE, new OrderField[] { TemplateStore.TEMPLATE_STORE.ID }, true);
        public static Index TERMINOLOGY_PROVIDER_PKEY = Internal.createIndex("terminology_provider_pkey", TerminologyProvider.TERMINOLOGY_PROVIDER, new OrderField[] { TerminologyProvider.TERMINOLOGY_PROVIDER.CODE }, true);
        public static Index TERRITORY_CODE_INDEX = Internal.createIndex("territory_code_index", Territory.TERRITORY, new OrderField[] { Territory.TERRITORY.CODE }, true);
        public static Index TERRITORY_PKEY = Internal.createIndex("territory_pkey", Territory.TERRITORY, new OrderField[] { Territory.TERRITORY.CODE }, true);
    }
}
