/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.udt.CodePhrase;
import org.ehrbase.jooq.pg.udt.DvCodedText;


/**
 * Convenience access to all UDTs in ehr
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>ehr.code_phrase</code>
     */
    public static CodePhrase CODE_PHRASE = CodePhrase.CODE_PHRASE;

    /**
     * The type <code>ehr.dv_coded_text</code>
     */
    public static DvCodedText DV_CODED_TEXT = DvCodedText.DV_CODED_TEXT;
}
