/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.Indexes;
import org.ehrbase.jooq.pg.Keys;
import org.ehrbase.jooq.pg.tables.records.AccessRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Access extends TableImpl<AccessRecord> {

    private static final long serialVersionUID = 267297430;

    /**
     * The reference instance of <code>ehr.access</code>
     */
    public static final Access ACCESS = new Access();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccessRecord> getRecordType() {
        return AccessRecord.class;
    }

    /**
     * The column <code>ehr.access.id</code>.
     */
    public final TableField<AccessRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>ehr.access.settings</code>.
     */
    public final TableField<AccessRecord, String> SETTINGS = createField(DSL.name("settings"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.access.scheme</code>.
     */
    public final TableField<AccessRecord, String> SCHEME = createField(DSL.name("scheme"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>ehr.access</code> table reference
     */
    public Access() {
        this(DSL.name("access"), null);
    }

    /**
     * Create an aliased <code>ehr.access</code> table reference
     */
    public Access(String alias) {
        this(DSL.name(alias), ACCESS);
    }

    /**
     * Create an aliased <code>ehr.access</code> table reference
     */
    public Access(Name alias) {
        this(alias, ACCESS);
    }

    private Access(Name alias, Table<AccessRecord> aliased) {
        this(alias, aliased, null);
    }

    private Access(Name alias, Table<AccessRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Access(Table<O> child, ForeignKey<O, AccessRecord> key) {
        super(child, key, ACCESS);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCESS_PKEY);
    }

    @Override
    public UniqueKey<AccessRecord> getPrimaryKey() {
        return Keys.ACCESS_PKEY;
    }

    @Override
    public List<UniqueKey<AccessRecord>> getKeys() {
        return Arrays.<UniqueKey<AccessRecord>>asList(Keys.ACCESS_PKEY);
    }

    @Override
    public Access as(String alias) {
        return new Access(DSL.name(alias), this);
    }

    @Override
    public Access as(Name alias) {
        return new Access(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Access rename(String name) {
        return new Access(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Access rename(Name name) {
        return new Access(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
