/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminDeleteEhrHistoryRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteEhrHistory extends TableImpl<AdminDeleteEhrHistoryRecord> {

    private static final long serialVersionUID = -1151300137;

    /**
     * The reference instance of <code>ehr.admin_delete_ehr_history</code>
     */
    public static final AdminDeleteEhrHistory ADMIN_DELETE_EHR_HISTORY = new AdminDeleteEhrHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminDeleteEhrHistoryRecord> getRecordType() {
        return AdminDeleteEhrHistoryRecord.class;
    }

    /**
     * The column <code>ehr.admin_delete_ehr_history.num</code>.
     */
    public final TableField<AdminDeleteEhrHistoryRecord, Integer> NUM = createField(DSL.name("num"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>ehr.admin_delete_ehr_history</code> table reference
     */
    public AdminDeleteEhrHistory() {
        this(DSL.name("admin_delete_ehr_history"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_ehr_history</code> table reference
     */
    public AdminDeleteEhrHistory(String alias) {
        this(DSL.name(alias), ADMIN_DELETE_EHR_HISTORY);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_ehr_history</code> table reference
     */
    public AdminDeleteEhrHistory(Name alias) {
        this(alias, ADMIN_DELETE_EHR_HISTORY);
    }

    private AdminDeleteEhrHistory(Name alias, Table<AdminDeleteEhrHistoryRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminDeleteEhrHistory(Name alias, Table<AdminDeleteEhrHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminDeleteEhrHistory(Table<O> child, ForeignKey<O, AdminDeleteEhrHistoryRecord> key) {
        super(child, key, ADMIN_DELETE_EHR_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminDeleteEhrHistory as(String alias) {
        return new AdminDeleteEhrHistory(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminDeleteEhrHistory as(Name alias) {
        return new AdminDeleteEhrHistory(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteEhrHistory rename(String name) {
        return new AdminDeleteEhrHistory(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteEhrHistory rename(Name name) {
        return new AdminDeleteEhrHistory(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteEhrHistory call(UUID ehrIdInput) {
        return new AdminDeleteEhrHistory(DSL.name(getName()), null, new Field[] { 
              DSL.val(ehrIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteEhrHistory call(Field<UUID> ehrIdInput) {
        return new AdminDeleteEhrHistory(DSL.name(getName()), null, new Field[] { 
              ehrIdInput
        });
    }
}
