/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminDeleteCompositionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteComposition extends TableImpl<AdminDeleteCompositionRecord> {

    private static final long serialVersionUID = 1469980325;

    /**
     * The reference instance of <code>ehr.admin_delete_composition</code>
     */
    public static final AdminDeleteComposition ADMIN_DELETE_COMPOSITION = new AdminDeleteComposition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminDeleteCompositionRecord> getRecordType() {
        return AdminDeleteCompositionRecord.class;
    }

    /**
     * The column <code>ehr.admin_delete_composition.num</code>.
     */
    public final TableField<AdminDeleteCompositionRecord, Integer> NUM = createField(DSL.name("num"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ehr.admin_delete_composition.contribution</code>.
     */
    public final TableField<AdminDeleteCompositionRecord, UUID> CONTRIBUTION = createField(DSL.name("contribution"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_delete_composition.party</code>.
     */
    public final TableField<AdminDeleteCompositionRecord, UUID> PARTY = createField(DSL.name("party"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_delete_composition.audit</code>.
     */
    public final TableField<AdminDeleteCompositionRecord, UUID> AUDIT = createField(DSL.name("audit"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_delete_composition.attestation</code>.
     */
    public final TableField<AdminDeleteCompositionRecord, UUID> ATTESTATION = createField(DSL.name("attestation"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_delete_composition</code> table reference
     */
    public AdminDeleteComposition() {
        this(DSL.name("admin_delete_composition"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_composition</code> table reference
     */
    public AdminDeleteComposition(String alias) {
        this(DSL.name(alias), ADMIN_DELETE_COMPOSITION);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_composition</code> table reference
     */
    public AdminDeleteComposition(Name alias) {
        this(alias, ADMIN_DELETE_COMPOSITION);
    }

    private AdminDeleteComposition(Name alias, Table<AdminDeleteCompositionRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminDeleteComposition(Name alias, Table<AdminDeleteCompositionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminDeleteComposition(Table<O> child, ForeignKey<O, AdminDeleteCompositionRecord> key) {
        super(child, key, ADMIN_DELETE_COMPOSITION);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminDeleteComposition as(String alias) {
        return new AdminDeleteComposition(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminDeleteComposition as(Name alias) {
        return new AdminDeleteComposition(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteComposition rename(String name) {
        return new AdminDeleteComposition(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteComposition rename(Name name) {
        return new AdminDeleteComposition(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, UUID, UUID, UUID, UUID> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteComposition call(UUID compoIdInput) {
        return new AdminDeleteComposition(DSL.name(getName()), null, new Field[] { 
              DSL.val(compoIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteComposition call(Field<UUID> compoIdInput) {
        return new AdminDeleteComposition(DSL.name(getName()), null, new Field[] { 
              compoIdInput
        });
    }
}
