/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminGetLinkedCompositionsForContribRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminGetLinkedCompositionsForContrib extends TableImpl<AdminGetLinkedCompositionsForContribRecord> {

    private static final long serialVersionUID = 431987968;

    /**
     * The reference instance of <code>ehr.admin_get_linked_compositions_for_contrib</code>
     */
    public static final AdminGetLinkedCompositionsForContrib ADMIN_GET_LINKED_COMPOSITIONS_FOR_CONTRIB = new AdminGetLinkedCompositionsForContrib();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminGetLinkedCompositionsForContribRecord> getRecordType() {
        return AdminGetLinkedCompositionsForContribRecord.class;
    }

    /**
     * The column <code>ehr.admin_get_linked_compositions_for_contrib.composition</code>.
     */
    public final TableField<AdminGetLinkedCompositionsForContribRecord, UUID> COMPOSITION = createField(DSL.name("composition"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_get_linked_compositions_for_contrib</code> table reference
     */
    public AdminGetLinkedCompositionsForContrib() {
        this(DSL.name("admin_get_linked_compositions_for_contrib"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_compositions_for_contrib</code> table reference
     */
    public AdminGetLinkedCompositionsForContrib(String alias) {
        this(DSL.name(alias), ADMIN_GET_LINKED_COMPOSITIONS_FOR_CONTRIB);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_compositions_for_contrib</code> table reference
     */
    public AdminGetLinkedCompositionsForContrib(Name alias) {
        this(alias, ADMIN_GET_LINKED_COMPOSITIONS_FOR_CONTRIB);
    }

    private AdminGetLinkedCompositionsForContrib(Name alias, Table<AdminGetLinkedCompositionsForContribRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminGetLinkedCompositionsForContrib(Name alias, Table<AdminGetLinkedCompositionsForContribRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminGetLinkedCompositionsForContrib(Table<O> child, ForeignKey<O, AdminGetLinkedCompositionsForContribRecord> key) {
        super(child, key, ADMIN_GET_LINKED_COMPOSITIONS_FOR_CONTRIB);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminGetLinkedCompositionsForContrib as(String alias) {
        return new AdminGetLinkedCompositionsForContrib(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminGetLinkedCompositionsForContrib as(Name alias) {
        return new AdminGetLinkedCompositionsForContrib(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedCompositionsForContrib rename(String name) {
        return new AdminGetLinkedCompositionsForContrib(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedCompositionsForContrib rename(Name name) {
        return new AdminGetLinkedCompositionsForContrib(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<UUID> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedCompositionsForContrib call(UUID contribIdInput) {
        return new AdminGetLinkedCompositionsForContrib(DSL.name(getName()), null, new Field[] { 
              DSL.val(contribIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedCompositionsForContrib call(Field<UUID> contribIdInput) {
        return new AdminGetLinkedCompositionsForContrib(DSL.name(getName()), null, new Field[] { 
              contribIdInput
        });
    }
}
