/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminGetTemplateUsageRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminGetTemplateUsage extends TableImpl<AdminGetTemplateUsageRecord> {

    private static final long serialVersionUID = 2048529406;

    /**
     * The reference instance of <code>ehr.admin_get_template_usage</code>
     */
    public static final AdminGetTemplateUsage ADMIN_GET_TEMPLATE_USAGE = new AdminGetTemplateUsage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminGetTemplateUsageRecord> getRecordType() {
        return AdminGetTemplateUsageRecord.class;
    }

    /**
     * The column <code>ehr.admin_get_template_usage.composition_id</code>.
     */
    public final TableField<AdminGetTemplateUsageRecord, UUID> COMPOSITION_ID = createField(DSL.name("composition_id"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_get_template_usage</code> table reference
     */
    public AdminGetTemplateUsage() {
        this(DSL.name("admin_get_template_usage"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_get_template_usage</code> table reference
     */
    public AdminGetTemplateUsage(String alias) {
        this(DSL.name(alias), ADMIN_GET_TEMPLATE_USAGE);
    }

    /**
     * Create an aliased <code>ehr.admin_get_template_usage</code> table reference
     */
    public AdminGetTemplateUsage(Name alias) {
        this(alias, ADMIN_GET_TEMPLATE_USAGE);
    }

    private AdminGetTemplateUsage(Name alias, Table<AdminGetTemplateUsageRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminGetTemplateUsage(Name alias, Table<AdminGetTemplateUsageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminGetTemplateUsage(Table<O> child, ForeignKey<O, AdminGetTemplateUsageRecord> key) {
        super(child, key, ADMIN_GET_TEMPLATE_USAGE);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminGetTemplateUsage as(String alias) {
        return new AdminGetTemplateUsage(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminGetTemplateUsage as(Name alias) {
        return new AdminGetTemplateUsage(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetTemplateUsage rename(String name) {
        return new AdminGetTemplateUsage(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetTemplateUsage rename(Name name) {
        return new AdminGetTemplateUsage(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<UUID> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminGetTemplateUsage call(String targetId) {
        return new AdminGetTemplateUsage(DSL.name(getName()), null, new Field[] { 
              DSL.val(targetId, org.jooq.impl.SQLDataType.CLOB)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminGetTemplateUsage call(Field<String> targetId) {
        return new AdminGetTemplateUsage(DSL.name(getName()), null, new Field[] { 
              targetId
        });
    }
}
