/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminGetLinkedCompositionsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminGetLinkedCompositions extends TableImpl<AdminGetLinkedCompositionsRecord> {

    private static final long serialVersionUID = -476202976;

    /**
     * The reference instance of <code>ehr.admin_get_linked_compositions</code>
     */
    public static final AdminGetLinkedCompositions ADMIN_GET_LINKED_COMPOSITIONS = new AdminGetLinkedCompositions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminGetLinkedCompositionsRecord> getRecordType() {
        return AdminGetLinkedCompositionsRecord.class;
    }

    /**
     * The column <code>ehr.admin_get_linked_compositions.composition</code>.
     */
    public final TableField<AdminGetLinkedCompositionsRecord, UUID> COMPOSITION = createField(DSL.name("composition"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_get_linked_compositions</code> table reference
     */
    public AdminGetLinkedCompositions() {
        this(DSL.name("admin_get_linked_compositions"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_compositions</code> table reference
     */
    public AdminGetLinkedCompositions(String alias) {
        this(DSL.name(alias), ADMIN_GET_LINKED_COMPOSITIONS);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_compositions</code> table reference
     */
    public AdminGetLinkedCompositions(Name alias) {
        this(alias, ADMIN_GET_LINKED_COMPOSITIONS);
    }

    private AdminGetLinkedCompositions(Name alias, Table<AdminGetLinkedCompositionsRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminGetLinkedCompositions(Name alias, Table<AdminGetLinkedCompositionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminGetLinkedCompositions(Table<O> child, ForeignKey<O, AdminGetLinkedCompositionsRecord> key) {
        super(child, key, ADMIN_GET_LINKED_COMPOSITIONS);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminGetLinkedCompositions as(String alias) {
        return new AdminGetLinkedCompositions(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminGetLinkedCompositions as(Name alias) {
        return new AdminGetLinkedCompositions(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedCompositions rename(String name) {
        return new AdminGetLinkedCompositions(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedCompositions rename(Name name) {
        return new AdminGetLinkedCompositions(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<UUID> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedCompositions call(UUID ehrIdInput) {
        return new AdminGetLinkedCompositions(DSL.name(getName()), null, new Field[] { 
              DSL.val(ehrIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedCompositions call(Field<UUID> ehrIdInput) {
        return new AdminGetLinkedCompositions(DSL.name(getName()), null, new Field[] { 
              ehrIdInput
        });
    }
}
