/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminDeleteStatusHistoryRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteStatusHistory extends TableImpl<AdminDeleteStatusHistoryRecord> {

    private static final long serialVersionUID = -534907672;

    /**
     * The reference instance of <code>ehr.admin_delete_status_history</code>
     */
    public static final AdminDeleteStatusHistory ADMIN_DELETE_STATUS_HISTORY = new AdminDeleteStatusHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminDeleteStatusHistoryRecord> getRecordType() {
        return AdminDeleteStatusHistoryRecord.class;
    }

    /**
     * The column <code>ehr.admin_delete_status_history.num</code>.
     */
    public final TableField<AdminDeleteStatusHistoryRecord, Integer> NUM = createField(DSL.name("num"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>ehr.admin_delete_status_history</code> table reference
     */
    public AdminDeleteStatusHistory() {
        this(DSL.name("admin_delete_status_history"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_status_history</code> table reference
     */
    public AdminDeleteStatusHistory(String alias) {
        this(DSL.name(alias), ADMIN_DELETE_STATUS_HISTORY);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_status_history</code> table reference
     */
    public AdminDeleteStatusHistory(Name alias) {
        this(alias, ADMIN_DELETE_STATUS_HISTORY);
    }

    private AdminDeleteStatusHistory(Name alias, Table<AdminDeleteStatusHistoryRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminDeleteStatusHistory(Name alias, Table<AdminDeleteStatusHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminDeleteStatusHistory(Table<O> child, ForeignKey<O, AdminDeleteStatusHistoryRecord> key) {
        super(child, key, ADMIN_DELETE_STATUS_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminDeleteStatusHistory as(String alias) {
        return new AdminDeleteStatusHistory(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminDeleteStatusHistory as(Name alias) {
        return new AdminDeleteStatusHistory(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteStatusHistory rename(String name) {
        return new AdminDeleteStatusHistory(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteStatusHistory rename(Name name) {
        return new AdminDeleteStatusHistory(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteStatusHistory call(UUID statusIdInput) {
        return new AdminDeleteStatusHistory(DSL.name(getName()), null, new Field[] { 
              DSL.val(statusIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteStatusHistory call(Field<UUID> statusIdInput) {
        return new AdminDeleteStatusHistory(DSL.name(getName()), null, new Field[] { 
              statusIdInput
        });
    }
}
