/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminDeleteFolderHistoryRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteFolderHistory extends TableImpl<AdminDeleteFolderHistoryRecord> {

    private static final long serialVersionUID = -305861012;

    /**
     * The reference instance of <code>ehr.admin_delete_folder_history</code>
     */
    public static final AdminDeleteFolderHistory ADMIN_DELETE_FOLDER_HISTORY = new AdminDeleteFolderHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminDeleteFolderHistoryRecord> getRecordType() {
        return AdminDeleteFolderHistoryRecord.class;
    }

    /**
     * The column <code>ehr.admin_delete_folder_history.num</code>.
     */
    public final TableField<AdminDeleteFolderHistoryRecord, Integer> NUM = createField(DSL.name("num"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>ehr.admin_delete_folder_history</code> table reference
     */
    public AdminDeleteFolderHistory() {
        this(DSL.name("admin_delete_folder_history"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_folder_history</code> table reference
     */
    public AdminDeleteFolderHistory(String alias) {
        this(DSL.name(alias), ADMIN_DELETE_FOLDER_HISTORY);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_folder_history</code> table reference
     */
    public AdminDeleteFolderHistory(Name alias) {
        this(alias, ADMIN_DELETE_FOLDER_HISTORY);
    }

    private AdminDeleteFolderHistory(Name alias, Table<AdminDeleteFolderHistoryRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminDeleteFolderHistory(Name alias, Table<AdminDeleteFolderHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminDeleteFolderHistory(Table<O> child, ForeignKey<O, AdminDeleteFolderHistoryRecord> key) {
        super(child, key, ADMIN_DELETE_FOLDER_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminDeleteFolderHistory as(String alias) {
        return new AdminDeleteFolderHistory(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminDeleteFolderHistory as(Name alias) {
        return new AdminDeleteFolderHistory(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteFolderHistory rename(String name) {
        return new AdminDeleteFolderHistory(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteFolderHistory rename(Name name) {
        return new AdminDeleteFolderHistory(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteFolderHistory call(UUID folderIdInput) {
        return new AdminDeleteFolderHistory(DSL.name(getName()), null, new Field[] { 
              DSL.val(folderIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteFolderHistory call(Field<UUID> folderIdInput) {
        return new AdminDeleteFolderHistory(DSL.name(getName()), null, new Field[] { 
              folderIdInput
        });
    }
}
