/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminDeleteFolderRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteFolder extends TableImpl<AdminDeleteFolderRecord> {

    private static final long serialVersionUID = 201187676;

    /**
     * The reference instance of <code>ehr.admin_delete_folder</code>
     */
    public static final AdminDeleteFolder ADMIN_DELETE_FOLDER = new AdminDeleteFolder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminDeleteFolderRecord> getRecordType() {
        return AdminDeleteFolderRecord.class;
    }

    /**
     * The column <code>ehr.admin_delete_folder.contribution</code>.
     */
    public final TableField<AdminDeleteFolderRecord, UUID> CONTRIBUTION = createField(DSL.name("contribution"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_delete_folder.child</code>.
     */
    public final TableField<AdminDeleteFolderRecord, UUID> CHILD = createField(DSL.name("child"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_delete_folder.audit</code>.
     */
    public final TableField<AdminDeleteFolderRecord, UUID> AUDIT = createField(DSL.name("audit"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_delete_folder</code> table reference
     */
    public AdminDeleteFolder() {
        this(DSL.name("admin_delete_folder"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_folder</code> table reference
     */
    public AdminDeleteFolder(String alias) {
        this(DSL.name(alias), ADMIN_DELETE_FOLDER);
    }

    /**
     * Create an aliased <code>ehr.admin_delete_folder</code> table reference
     */
    public AdminDeleteFolder(Name alias) {
        this(alias, ADMIN_DELETE_FOLDER);
    }

    private AdminDeleteFolder(Name alias, Table<AdminDeleteFolderRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminDeleteFolder(Name alias, Table<AdminDeleteFolderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminDeleteFolder(Table<O> child, ForeignKey<O, AdminDeleteFolderRecord> key) {
        super(child, key, ADMIN_DELETE_FOLDER);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminDeleteFolder as(String alias) {
        return new AdminDeleteFolder(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminDeleteFolder as(Name alias) {
        return new AdminDeleteFolder(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteFolder rename(String name) {
        return new AdminDeleteFolder(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminDeleteFolder rename(Name name) {
        return new AdminDeleteFolder(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteFolder call(UUID folderIdInput) {
        return new AdminDeleteFolder(DSL.name(getName()), null, new Field[] { 
              DSL.val(folderIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminDeleteFolder call(Field<UUID> folderIdInput) {
        return new AdminDeleteFolder(DSL.name(getName()), null, new Field[] { 
              folderIdInput
        });
    }
}
