/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.AdminGetLinkedContributionsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminGetLinkedContributions extends TableImpl<AdminGetLinkedContributionsRecord> {

    private static final long serialVersionUID = 449231843;

    /**
     * The reference instance of <code>ehr.admin_get_linked_contributions</code>
     */
    public static final AdminGetLinkedContributions ADMIN_GET_LINKED_CONTRIBUTIONS = new AdminGetLinkedContributions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminGetLinkedContributionsRecord> getRecordType() {
        return AdminGetLinkedContributionsRecord.class;
    }

    /**
     * The column <code>ehr.admin_get_linked_contributions.contribution</code>.
     */
    public final TableField<AdminGetLinkedContributionsRecord, UUID> CONTRIBUTION = createField(DSL.name("contribution"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.admin_get_linked_contributions.audit</code>.
     */
    public final TableField<AdminGetLinkedContributionsRecord, UUID> AUDIT = createField(DSL.name("audit"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.admin_get_linked_contributions</code> table reference
     */
    public AdminGetLinkedContributions() {
        this(DSL.name("admin_get_linked_contributions"), null);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_contributions</code> table reference
     */
    public AdminGetLinkedContributions(String alias) {
        this(DSL.name(alias), ADMIN_GET_LINKED_CONTRIBUTIONS);
    }

    /**
     * Create an aliased <code>ehr.admin_get_linked_contributions</code> table reference
     */
    public AdminGetLinkedContributions(Name alias) {
        this(alias, ADMIN_GET_LINKED_CONTRIBUTIONS);
    }

    private AdminGetLinkedContributions(Name alias, Table<AdminGetLinkedContributionsRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private AdminGetLinkedContributions(Name alias, Table<AdminGetLinkedContributionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdminGetLinkedContributions(Table<O> child, ForeignKey<O, AdminGetLinkedContributionsRecord> key) {
        super(child, key, ADMIN_GET_LINKED_CONTRIBUTIONS);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public AdminGetLinkedContributions as(String alias) {
        return new AdminGetLinkedContributions(DSL.name(alias), this, parameters);
    }

    @Override
    public AdminGetLinkedContributions as(Name alias) {
        return new AdminGetLinkedContributions(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedContributions rename(String name) {
        return new AdminGetLinkedContributions(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminGetLinkedContributions rename(Name name) {
        return new AdminGetLinkedContributions(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedContributions call(UUID ehrIdInput) {
        return new AdminGetLinkedContributions(DSL.name(getName()), null, new Field[] { 
              DSL.val(ehrIdInput, org.jooq.impl.SQLDataType.UUID)
        });
    }

    /**
     * Call this table-valued function
     */
    public AdminGetLinkedContributions call(Field<UUID> ehrIdInput) {
        return new AdminGetLinkedContributions(DSL.name(getName()), null, new Field[] { 
              ehrIdInput
        });
    }
}
