/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Indexes;
import org.ehrbase.jooq.pg.Keys;
import org.ehrbase.jooq.pg.tables.records.EhrRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ehr extends TableImpl<EhrRecord> {

    private static final long serialVersionUID = -331641613;

    /**
     * The reference instance of <code>ehr.ehr</code>
     */
    public static final Ehr EHR_ = new Ehr();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhrRecord> getRecordType() {
        return EhrRecord.class;
    }

    /**
     * The column <code>ehr.ehr.id</code>.
     */
    public final TableField<EhrRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>ehr.ehr.date_created</code>.
     */
    public final TableField<EhrRecord, Timestamp> DATE_CREATED = createField(DSL.name("date_created"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_DATE", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ehr.ehr.date_created_tzid</code>.
     */
    public final TableField<EhrRecord, String> DATE_CREATED_TZID = createField(DSL.name("date_created_tzid"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr.access</code>.
     */
    public final TableField<EhrRecord, UUID> ACCESS = createField(DSL.name("access"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.ehr.system_id</code>.
     */
    public final TableField<EhrRecord, UUID> SYSTEM_ID = createField(DSL.name("system_id"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>ehr.ehr.directory</code>.
     */
    public final TableField<EhrRecord, UUID> DIRECTORY = createField(DSL.name("directory"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>ehr.ehr</code> table reference
     */
    public Ehr() {
        this(DSL.name("ehr"), null);
    }

    /**
     * Create an aliased <code>ehr.ehr</code> table reference
     */
    public Ehr(String alias) {
        this(DSL.name(alias), EHR_);
    }

    /**
     * Create an aliased <code>ehr.ehr</code> table reference
     */
    public Ehr(Name alias) {
        this(alias, EHR_);
    }

    private Ehr(Name alias, Table<EhrRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ehr(Name alias, Table<EhrRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Ehr(Table<O> child, ForeignKey<O, EhrRecord> key) {
        super(child, key, EHR_);
    }

    @Override
    public Schema getSchema() {
        return org.ehrbase.jooq.pg.Ehr.EHR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EHR_FOLDER_IDX, Indexes.EHR_PKEY);
    }

    @Override
    public UniqueKey<EhrRecord> getPrimaryKey() {
        return Keys.EHR_PKEY;
    }

    @Override
    public List<UniqueKey<EhrRecord>> getKeys() {
        return Arrays.<UniqueKey<EhrRecord>>asList(Keys.EHR_PKEY);
    }

    @Override
    public List<ForeignKey<EhrRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EhrRecord, ?>>asList(Keys.EHR__EHR_ACCESS_FKEY, Keys.EHR__EHR_SYSTEM_ID_FKEY, Keys.EHR__EHR_DIRECTORY_FKEY);
    }

    public Access access() {
        return new Access(this, Keys.EHR__EHR_ACCESS_FKEY);
    }

    public System system() {
        return new System(this, Keys.EHR__EHR_SYSTEM_ID_FKEY);
    }

    public Folder folder() {
        return new Folder(this, Keys.EHR__EHR_DIRECTORY_FKEY);
    }

    @Override
    public Ehr as(String alias) {
        return new Ehr(DSL.name(alias), this);
    }

    @Override
    public Ehr as(Name alias) {
        return new Ehr(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ehr rename(String name) {
        return new Ehr(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ehr rename(Name name) {
        return new Ehr(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, Timestamp, String, UUID, UUID, UUID> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
