/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.tables.records.JsonbArrayElementsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonbArrayElements extends TableImpl<JsonbArrayElementsRecord> {

    private static final long serialVersionUID = 1174379776;

    /**
     * The reference instance of <code>ehr.jsonb_array_elements</code>
     */
    public static final JsonbArrayElements JSONB_ARRAY_ELEMENTS = new JsonbArrayElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JsonbArrayElementsRecord> getRecordType() {
        return JsonbArrayElementsRecord.class;
    }

    /**
     * The column <code>ehr.jsonb_array_elements.jsonb_array_elements</code>.
     */
    public final TableField<JsonbArrayElementsRecord, JSONB> JSONB_ARRAY_ELEMENTS_ = createField(DSL.name("jsonb_array_elements"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * Create a <code>ehr.jsonb_array_elements</code> table reference
     */
    public JsonbArrayElements() {
        this(DSL.name("jsonb_array_elements"), null);
    }

    /**
     * Create an aliased <code>ehr.jsonb_array_elements</code> table reference
     */
    public JsonbArrayElements(String alias) {
        this(DSL.name(alias), JSONB_ARRAY_ELEMENTS);
    }

    /**
     * Create an aliased <code>ehr.jsonb_array_elements</code> table reference
     */
    public JsonbArrayElements(Name alias) {
        this(alias, JSONB_ARRAY_ELEMENTS);
    }

    private JsonbArrayElements(Name alias, Table<JsonbArrayElementsRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private JsonbArrayElements(Name alias, Table<JsonbArrayElementsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JsonbArrayElements(Table<O> child, ForeignKey<O, JsonbArrayElementsRecord> key) {
        super(child, key, JSONB_ARRAY_ELEMENTS);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public JsonbArrayElements as(String alias) {
        return new JsonbArrayElements(DSL.name(alias), this, parameters);
    }

    @Override
    public JsonbArrayElements as(Name alias) {
        return new JsonbArrayElements(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public JsonbArrayElements rename(String name) {
        return new JsonbArrayElements(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public JsonbArrayElements rename(Name name) {
        return new JsonbArrayElements(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<JSONB> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public JsonbArrayElements call(JSONB jsonbVal) {
        return new JsonbArrayElements(DSL.name(getName()), null, new Field[] { 
              DSL.val(jsonbVal, org.jooq.impl.SQLDataType.JSONB)
        });
    }

    /**
     * Call this table-valued function
     */
    public JsonbArrayElements call(Field<JSONB> jsonbVal) {
        return new JsonbArrayElements(DSL.name(getName()), null, new Field[] { 
              jsonbVal
        });
    }
}
