/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.Indexes;
import org.ehrbase.jooq.pg.Keys;
import org.ehrbase.jooq.pg.tables.records.TerritoryRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Territory extends TableImpl<TerritoryRecord> {

    private static final long serialVersionUID = 299720857;

    /**
     * The reference instance of <code>ehr.territory</code>
     */
    public static final Territory TERRITORY = new Territory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TerritoryRecord> getRecordType() {
        return TerritoryRecord.class;
    }

    /**
     * The column <code>ehr.territory.code</code>.
     */
    public final TableField<TerritoryRecord, Integer> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.territory.twoletter</code>.
     */
    public final TableField<TerritoryRecord, String> TWOLETTER = createField(DSL.name("twoletter"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>ehr.territory.threeletter</code>.
     */
    public final TableField<TerritoryRecord, String> THREELETTER = createField(DSL.name("threeletter"), org.jooq.impl.SQLDataType.CHAR(3), this, "");

    /**
     * The column <code>ehr.territory.text</code>.
     */
    public final TableField<TerritoryRecord, String> TEXT = createField(DSL.name("text"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>ehr.territory</code> table reference
     */
    public Territory() {
        this(DSL.name("territory"), null);
    }

    /**
     * Create an aliased <code>ehr.territory</code> table reference
     */
    public Territory(String alias) {
        this(DSL.name(alias), TERRITORY);
    }

    /**
     * Create an aliased <code>ehr.territory</code> table reference
     */
    public Territory(Name alias) {
        this(alias, TERRITORY);
    }

    private Territory(Name alias, Table<TerritoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Territory(Name alias, Table<TerritoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Territory(Table<O> child, ForeignKey<O, TerritoryRecord> key) {
        super(child, key, TERRITORY);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TERRITORY_CODE_INDEX, Indexes.TERRITORY_PKEY);
    }

    @Override
    public UniqueKey<TerritoryRecord> getPrimaryKey() {
        return Keys.TERRITORY_PKEY;
    }

    @Override
    public List<UniqueKey<TerritoryRecord>> getKeys() {
        return Arrays.<UniqueKey<TerritoryRecord>>asList(Keys.TERRITORY_PKEY);
    }

    @Override
    public Territory as(String alias) {
        return new Territory(DSL.name(alias), this);
    }

    @Override
    public Territory as(Name alias) {
        return new Territory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Territory rename(String name) {
        return new Territory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Territory rename(Name name) {
        return new Territory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
