/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminUpdateTemplate extends AbstractRoutine<String> {

    private static final long serialVersionUID = -347054445;

    /**
     * The parameter <code>ehr.admin_update_template.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>ehr.admin_update_template.target_id</code>.
     */
    public static final Parameter<String> TARGET_ID = Internal.createParameter("target_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>ehr.admin_update_template.update_content</code>.
     */
    public static final Parameter<String> UPDATE_CONTENT = Internal.createParameter("update_content", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public AdminUpdateTemplate() {
        super("admin_update_template", Ehr.EHR, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TARGET_ID);
        addInParameter(UPDATE_CONTENT);
    }

    /**
     * Set the <code>target_id</code> parameter IN value to the routine
     */
    public void setTargetId(String value) {
        setValue(TARGET_ID, value);
    }

    /**
     * Set the <code>target_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTargetId(Field<String> field) {
        setField(TARGET_ID, field);
    }

    /**
     * Set the <code>update_content</code> parameter IN value to the routine
     */
    public void setUpdateContent(String value) {
        setValue(UPDATE_CONTENT, value);
    }

    /**
     * Set the <code>update_content</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUpdateContent(Field<String> field) {
        setField(UPDATE_CONTENT, field);
    }
}
