/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteTemplate extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 2011176512;

    /**
     * The parameter <code>ehr.admin_delete_template.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>ehr.admin_delete_template.target_id</code>.
     */
    public static final Parameter<String> TARGET_ID = Internal.createParameter("target_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public AdminDeleteTemplate() {
        super("admin_delete_template", Ehr.EHR, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TARGET_ID);
    }

    /**
     * Set the <code>target_id</code> parameter IN value to the routine
     */
    public void setTargetId(String value) {
        setValue(TARGET_ID, value);
    }

    /**
     * Set the <code>target_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTargetId(Field<String> field) {
        setField(TARGET_ID, field);
    }
}
