/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsCanonicalPartyIdentified extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = -522209624;

    /**
     * The parameter <code>ehr.js_canonical_party_identified.RETURN_VALUE</code>.
     */
    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.JSON, false, false);

    /**
     * The parameter <code>ehr.js_canonical_party_identified.refid</code>.
     */
    public static final Parameter<UUID> REFID = Internal.createParameter("refid", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public JsCanonicalPartyIdentified() {
        super("js_canonical_party_identified", Ehr.EHR, org.jooq.impl.SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(REFID);
    }

    /**
     * Set the <code>refid</code> parameter IN value to the routine
     */
    public void setRefid(UUID value) {
        setValue(REFID, value);
    }

    /**
     * Set the <code>refid</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setRefid(Field<UUID> field) {
        setField(REFID, field);
    }
}
