/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsEhrStatus2 extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = -471800301;

    /**
     * The parameter <code>ehr.js_ehr_status.RETURN_VALUE</code>.
     */
    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.JSON, false, false);

    /**
     * The parameter <code>ehr.js_ehr_status.ehr_uuid</code>.
     */
    public static final Parameter<UUID> EHR_UUID = Internal.createParameter("ehr_uuid", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * The parameter <code>ehr.js_ehr_status.server_id</code>.
     */
    public static final Parameter<String> SERVER_ID = Internal.createParameter("server_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public JsEhrStatus2() {
        super("js_ehr_status", Ehr.EHR, org.jooq.impl.SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(EHR_UUID);
        addInParameter(SERVER_ID);
        setOverloaded(true);
    }

    /**
     * Set the <code>ehr_uuid</code> parameter IN value to the routine
     */
    public void setEhrUuid(UUID value) {
        setValue(EHR_UUID, value);
    }

    /**
     * Set the <code>ehr_uuid</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setEhrUuid(Field<UUID> field) {
        setField(EHR_UUID, field);
    }

    /**
     * Set the <code>server_id</code> parameter IN value to the routine
     */
    public void setServerId(String value) {
        setValue(SERVER_ID, value);
    }

    /**
     * Set the <code>server_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setServerId(Field<String> field) {
        setField(SERVER_ID, field);
    }
}
