/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrateFolderAudit extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 565641069;

    /**
     * The parameter <code>ehr.migrate_folder_audit.ret_id</code>.
     */
    public static final Parameter<UUID> RET_ID = Internal.createParameter("ret_id", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public MigrateFolderAudit() {
        super("migrate_folder_audit", Ehr.EHR);

        addOutParameter(RET_ID);
    }

    /**
     * Get the <code>ret_id</code> parameter OUT value from the routine
     */
    public UUID getRetId() {
        return get(RET_ID);
    }
}
