/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import java.util.UUID;

import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyUsage extends AbstractRoutine<Long> {

    private static final long serialVersionUID = -1647905716;

    /**
     * The parameter <code>ehr.party_usage.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>ehr.party_usage.party_uuid</code>.
     */
    public static final Parameter<UUID> PARTY_UUID = Internal.createParameter("party_uuid", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public PartyUsage() {
        super("party_usage", Ehr.EHR, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(PARTY_UUID);
    }

    /**
     * Set the <code>party_uuid</code> parameter IN value to the routine
     */
    public void setPartyUuid(UUID value) {
        setValue(PARTY_UUID, value);
    }

    /**
     * Set the <code>party_uuid</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPartyUuid(Field<UUID> field) {
        setField(PARTY_UUID, field);
    }
}
