/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.udt;


import javax.annotation.processing.Generated;

import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.udt.records.CodePhraseRecord;
import org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord;
import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DvCodedText extends UDTImpl<DvCodedTextRecord> {

    private static final long serialVersionUID = -1715005019;

    /**
     * The reference instance of <code>ehr.dv_coded_text</code>
     */
    public static final DvCodedText DV_CODED_TEXT = new DvCodedText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DvCodedTextRecord> getRecordType() {
        return DvCodedTextRecord.class;
    }

    /**
     * The attribute <code>ehr.dv_coded_text.value</code>.
     */
    public static final UDTField<DvCodedTextRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.CLOB, DV_CODED_TEXT, "");

    /**
     * The attribute <code>ehr.dv_coded_text.defining_code</code>.
     */
    public static final UDTField<DvCodedTextRecord, CodePhraseRecord> DEFINING_CODE = createField(DSL.name("defining_code"), CodePhrase.CODE_PHRASE.getDataType(), DV_CODED_TEXT, "");

    /**
     * The attribute <code>ehr.dv_coded_text.formatting</code>.
     */
    public static final UDTField<DvCodedTextRecord, String> FORMATTING = createField(DSL.name("formatting"), org.jooq.impl.SQLDataType.CLOB, DV_CODED_TEXT, "");

    /**
     * The attribute <code>ehr.dv_coded_text.language</code>.
     */
    public static final UDTField<DvCodedTextRecord, CodePhraseRecord> LANGUAGE = createField(DSL.name("language"), CodePhrase.CODE_PHRASE.getDataType(), DV_CODED_TEXT, "");

    /**
     * The attribute <code>ehr.dv_coded_text.encoding</code>.
     */
    public static final UDTField<DvCodedTextRecord, CodePhraseRecord> ENCODING = createField(DSL.name("encoding"), CodePhrase.CODE_PHRASE.getDataType(), DV_CODED_TEXT, "");

    /**
     * The attribute <code>ehr.dv_coded_text.term_mapping</code>.
     */
    public static final UDTField<DvCodedTextRecord, String[]> TERM_MAPPING = createField(DSL.name("term_mapping"), org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), DV_CODED_TEXT, "");

    /**
     * No further instances allowed
     */
    private DvCodedText() {
        super("dv_coded_text", null, null, false);
    }

    @Override
    public Schema getSchema() {
        return Ehr.EHR != null ? Ehr.EHR : new SchemaImpl(DSL.name("ehr"));
    }
}
