name: build

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '.circleci/**'
      - '.docker_scripts/**'
      - '.github/**'
      - 'doc/**'
      - 'tests/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ehrbase-db:
        image: ehrbase/ehrbase-postgres:13.4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          EHRBASE_USER: ehrbase
          EHRBASE_PASSWORD: ehrbase

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'


